[build]
builder = "nixpacks"

[deploy]
startCommand = "node bot.js"
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/google-chrome"